##############################################################################################
#
#                              SlimeServerManagement by James090500
#
###############################################################################################

# The host for SSM
# default: 0.0.0.0
host: "0.0.0.0"

# The port for SSM
# default: 8080
port: 8080